### PR TITLE
added polling handler/runnable for periodic checks for http data

### PR DESCRIPTION
**Pull request by thequbit**

### CODE REVIEW

**Comment by thequbit** [comment]
This looks to close #9 

I used a Handler/Runnable to solve this since all of the heavy lifting is in IntentServices.  I placed it in the HomeActivity.

@reustonium let me know if you think this is okay, and then you can merge.

**Comment by thequbit** [comment]
Just realized this probably doesn't run if the activity is not running ( ie the app is closed ).  @reustonium can yo confirm?

**Comment by reustonium** [comment]
yeah this isn't the best way to do this.  You are correct this will only run while the app is open, and in that case each fragment already handles updating data onResume()

Can you clarify the purpose of this feature?  Is it to create a notification for the user that something new is up on the server? (e.g. a new assignment, etc)

**Comment by reustonium** [comment]
If you wanted to go native service, you probably want GCM for downstream messages.  This requires using googles servers to handle the messaging, not sure that is aligned with the project vision.

https://developer.android.com/google/gcm/gcm.html

Other options are from 3rd party providers like Parse (facebox).  I'm sure there is a way to roll your own, but really this needs to be server side functionality that sends a message to the android device (which has a broadcast receiver to handle it).

**Comment by thequbit** [comment]
We do not want to use anyone elses services other than our own for the time being.  I would need to do quite a bit more research to figure out how to keep the identity of people safe if we used Google' servers.

Hmm, so I really can't make a service that just sits and fires an event every 15 minutes that pulls down new notifications/assignments/stories and checks against the existing list and provides an android notification saying there is something new, and then launch the home activity when the user clicks the android notification?  That seems odd.

Can you confirm @reustonium ?

**Comment by reustonium** [comment]
this is uncharted territory for me, maybe an IntentService again here?

https://developer.android.com/training/run-background-service/create-service.html

**Comment by reustonium** [comment]
Alarm Manager?!?

http://www.sitepoint.com/scheduling-background-tasks-android/

**Comment by thequbit** [comment]
Yea, AlarmManager looks like our answer.  I'll implement and submit a new PR shortly.

Thanks for doing the leg work on that research @reustonium !

**Pull request closed without merging**
